// Taskdetail MongoDB Schema
const mongoose = require('mongoose');

// Define the schema based on the taskdetail data structure
const taskdetailSchema = new mongoose.Schema({
  SERIALKEY: { type: String, required: true, index: true },
  WHSEID: { type: String, required: true, index: true },
  TASKDETAILKEY: { type: String, required: true, index: true },
  TASKTYPE: { type: String, index: true },
  STORERKEY: { type: String, index: true },
  SKU: { type: String, index: true },
  LOT: String,
  UOM: String,
  UOMQTY: Number,
  QTY: Number,
  FROMLOC: String,
  LOGICALFROMLOC: String,
  FROMID: String,
  TOLOC: String,
  LOGICALTOLOC: String,
  TOID: String,
  CASEID: String,
  PICKMETHOD: String,
  STATUS: { type: String, index: true },
  STATUSMSG: String,
  PRIORITY: String,
  SOURCEPRIORITY: String,
  HOLDKEY: String,
  USERKEY: String,
  USERPOSITION: String,
  USERKEYOVERRIDE: String,
  STARTTIME: Date,
  ENDTIME: Date,
  SOURCETYPE: String,
  SOURCEKEY: String,
  PICKDETAILKEY: String,
  ORDERKEY: { type: String, index: true },
  ORDERLINENUMBER: String,
  LISTKEY: String,
  WAVEKEY: String,
  REASONKEY: String,
  MESSAGE01: String,
  MESSAGE02: String,
  MESSAGE03: String,
  FINALTOLOC: String,
  RELEASEDATE: Date,
  OPTBATCHID: String,
  OPTTASKSEQUENCE: String,
  OPTREPLENISHMENTUOM: String,
  OPTQTYLOCMINIMUM: String,
  OPTLOCATIONTYPE: String,
  OPTQTYLOCLIMIT: String,
  SEQNO: String,
  AMSTRATEGYKEY: String,
  STEPNUMBER: String,
  ADDDATE: Date,
  ADDWHO: String,
  EDITDATE: Date,
  EDITWHO: String,
  DOOR: String,
  ROUTE: String,
  STOP: String,
  PUTAWAYZONE: String,
  UASSGNNUMBER: String,
  EQUIPMENT: String,
  EQUIPMENTID: String,
  STANDARD: String,
  SUBTASK: String,
  CLUSTERKEY: String,
  TAREWGT: Number,
  NETWGT: Number,
  GROSSWGT: Number,
  ASSIGNMENTNUMBER: String,
  MAXNUMPERCLUSTERCARTON: String,
  PAID: String,
  BILLABLE: String,
  OWNERBILLTO: String,
  CHARGECODE: String,
  ACTUALTOLOC: String,
  ESTLABORSTD: String,
  ORIGINALSTARTTIME: Date,
  ORIGINALENDTIME: Date,
  ORIGINALPAID: String,
  PAYROLLCANCELED: String,
  COMMENTS: String,
  POSITION: String,
  PICKCONTPLACEMENT: String,
  RUNSEQUENCE: String,
  REQUESTEDSHIPDATE: Date,
  EXT_UDF_STR1: String,
  EXT_UDF_STR2: String,
  EXT_UDF_STR3: String,
  EXT_UDF_STR4: String,
  EXT_UDF_STR5: String,
  EXT_UDF_STR6: String,
  EXT_UDF_STR7: String,
  EXT_UDF_STR8: String,
  EXT_UDF_STR9: String,
  EXT_UDF_STR10: String,
  EXT_UDF_STR11: String,
  EXT_UDF_STR12: String,
  EXT_UDF_STR13: String,
  EXT_UDF_STR14: String,
  EXT_UDF_STR15: String,
  EXT_UDF_STR16: String,
  EXT_UDF_STR17: String,
  EXT_UDF_STR18: String,
  EXT_UDF_STR19: String,
  EXT_UDF_STR20: String,
  EXT_UDF_DATE1: Date,
  EXT_UDF_DATE2: Date,
  EXT_UDF_DATE3: Date,
  EXT_UDF_DATE4: Date,
  EXT_UDF_DATE5: Date,
  EXT_UDF_FLOAT1: Number,
  EXT_UDF_FLOAT2: Number,
  EXT_UDF_FLOAT3: Number,
  EXT_UDF_FLOAT4: Number,
  EXT_UDF_FLOAT5: Number,
  EXT_UDF_LKUP1: String,
  EXT_UDF_LKUP2: String,
  EXT_UDF_LKUP3: String,
  EXT_UDF_LKUP4: String,
  EXT_UDF_LKUP5: String,
  EXT_UDF_LKUP6: String,
  EXT_UDF_LKUP7: String,
  EXT_UDF_LKUP8: String,
  EXT_UDF_LKUP9: String,
  EXT_UDF_LKUP10: String,
  SCHEMA_REFERENCE: String,
  // Add metadata for sync tracking
  _syncDate: { type: Date, default: Date.now },
  _syncStatus: { type: String, default: 'synced' }
}, {
  // Enable timestamps
  timestamps: true,
  // Disable version key
  versionKey: false
});

// Create a compound index for efficient lookups
taskdetailSchema.index({ WHSEID: 1, TASKDETAILKEY: 1 }, { unique: true });

// Create a model from the schema
const TaskDetail = mongoose.models.TaskDetail || mongoose.model('TaskDetail', taskdetailSchema);

module.exports = TaskDetail;
