[build]
  functions = "functions"
  publish = "public"

[dev]
  functions = "functions"
  publish = "public"
  port = 8888
  autoLaunch = false

[functions]
  node_bundler = "esbuild"
  included_files = ["ION_Credentials/**"]
  external_node_modules = ["mongoose"]

# Increase function timeout for background functions
[functions."start-sync"]
  included_files = ["ION_Credentials/**"]

[functions."process-batch"]
  included_files = ["ION_Credentials/**"]

[functions."get-sync-status"]
  included_files = ["ION_Credentials/**"]
